apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: manuela-lineapp-mcs-
  generation: 1
  name: manuela-lineapp-mcs
  namespace: manuela-lineapp-mcs
spec:
  targetNamespaces:
  - manuela-lineapp-mcs